# Generated by Django 6.0.2 on 2026-02-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(help_text='Tuliskan detail acara di sini')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('tanggal', models.DateTimeField(help_text='Tanggal dan jam acara')),
                ('is_active', models.BooleanField(default=True, help_text='Centang jika acara masih akan datang')),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Pilih event yang berkaitan (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kegiatan.event')),
            ],
        ),
    ]
