# Generated by Django 6.0.2 on 2026-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekomendasiBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, help_text='Link gambar dari LibraryThing (opsional)', null=True)),
                ('cover_lokal', models.ImageField(blank=True, help_text='Upload gambar jika tidak ada link', null=True, upload_to='covers/')),
                ('ulasan', models.TextField(help_text='Deskripsi singkat atau alasan pustakawan merekomendasikan buku ini')),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal_ditambahkan'],
            },
        ),
    ]
